// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.EquinixMetal
{
    public static class GetMetro
    {
        /// <summary>
        /// Provides an Equinix Metal metro datasource.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using EquinixMetal = Pulumi.EquinixMetal;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var sv = Output.Create(EquinixMetal.GetMetro.InvokeAsync(new EquinixMetal.GetMetroArgs
        ///         {
        ///             Code = "sv",
        ///         }));
        ///         this.Id = sv.Apply(sv =&gt; sv.Id);
        ///     }
        /// 
        ///     [Output("id")]
        ///     public Output&lt;string&gt; Id { get; set; }
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetMetroResult> InvokeAsync(GetMetroArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetMetroResult>("equinix-metal:index/getMetro:getMetro", args ?? new GetMetroArgs(), options.WithVersion());
    }


    public sealed class GetMetroArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The metro code
        /// </summary>
        [Input("code", required: true)]
        public string Code { get; set; } = null!;

        public GetMetroArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetMetroResult
    {
        /// <summary>
        /// The code of the metro
        /// </summary>
        public readonly string Code;
        /// <summary>
        /// The country of the metro
        /// </summary>
        public readonly string Country;
        /// <summary>
        /// The ID of the metro
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the metro
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetMetroResult(
            string code,

            string country,

            string id,

            string name)
        {
            Code = code;
            Country = country;
            Id = id;
            Name = name;
        }
    }
}
