// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.equinixmetal;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.equinixmetal.ConnectionArgs;
import com.pulumi.equinixmetal.Utilities;
import com.pulumi.equinixmetal.inputs.ConnectionState;
import com.pulumi.equinixmetal.outputs.ConnectionPort;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Use this resource to request of create an Interconnection from [Equinix Fabric - software-defined interconnections](https://metal.equinix.com/developers/docs/networking/fabric/)
 * 
 * ## Example Usage
 * 
 */
@ResourceType(type="equinix-metal:index/connection:Connection")
public class Connection extends com.pulumi.resources.CustomResource {
    /**
     * Description for the connection resource
     * 
     */
    @Export(name="description", type=String.class, parameters={})
    private Output</* @Nullable */ String> description;

    /**
     * @return Description for the connection resource
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Facility where the connection will be created
     * 
     */
    @Export(name="facility", type=String.class, parameters={})
    private Output<String> facility;

    /**
     * @return Facility where the connection will be created
     * 
     */
    public Output<String> facility() {
        return this.facility;
    }
    /**
     * Metro where the connection will be created
     * 
     */
    @Export(name="metro", type=String.class, parameters={})
    private Output<String> metro;

    /**
     * @return Metro where the connection will be created
     * 
     */
    public Output<String> metro() {
        return this.metro;
    }
    /**
     * Mode for connections in IBX facilities with the dedicated type - standard or tunnel
     * 
     */
    @Export(name="mode", type=String.class, parameters={})
    private Output</* @Nullable */ String> mode;

    /**
     * @return Mode for connections in IBX facilities with the dedicated type - standard or tunnel
     * 
     */
    public Output<Optional<String>> mode() {
        return Codegen.optional(this.mode);
    }
    /**
     * Name of the connection resource
     * 
     */
    @Export(name="name", type=String.class, parameters={})
    private Output<String> name;

    /**
     * @return Name of the connection resource
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * ID of the organization responsible for the connection
     * 
     */
    @Export(name="organizationId", type=String.class, parameters={})
    private Output<String> organizationId;

    /**
     * @return ID of the organization responsible for the connection
     * 
     */
    public Output<String> organizationId() {
        return this.organizationId;
    }
    /**
     * List of connection ports - primary (`ports[0]`) and secondary (`ports[1]`). Schema of port is described in documentation of the equinix-metal.Connection datasource.
     * 
     */
    @Export(name="ports", type=List.class, parameters={ConnectionPort.class})
    private Output<List<ConnectionPort>> ports;

    /**
     * @return List of connection ports - primary (`ports[0]`) and secondary (`ports[1]`). Schema of port is described in documentation of the equinix-metal.Connection datasource.
     * 
     */
    public Output<List<ConnectionPort>> ports() {
        return this.ports;
    }
    /**
     * ID of the project where the connection is scoped to, must be set for shared connection
     * 
     */
    @Export(name="projectId", type=String.class, parameters={})
    private Output</* @Nullable */ String> projectId;

    /**
     * @return ID of the project where the connection is scoped to, must be set for shared connection
     * 
     */
    public Output<Optional<String>> projectId() {
        return Codegen.optional(this.projectId);
    }
    /**
     * Connection redundancy - redundant or primary
     * 
     */
    @Export(name="redundancy", type=String.class, parameters={})
    private Output<String> redundancy;

    /**
     * @return Connection redundancy - redundant or primary
     * 
     */
    public Output<String> redundancy() {
        return this.redundancy;
    }
    /**
     * Port speed in bits per second
     * 
     */
    @Export(name="speed", type=Integer.class, parameters={})
    private Output<Integer> speed;

    /**
     * @return Port speed in bits per second
     * 
     */
    public Output<Integer> speed() {
        return this.speed;
    }
    /**
     * Status of the connection resource
     * 
     */
    @Export(name="status", type=String.class, parameters={})
    private Output<String> status;

    /**
     * @return Status of the connection resource
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * String list of tags
     * 
     */
    @Export(name="tags", type=List.class, parameters={String.class})
    private Output</* @Nullable */ List<String>> tags;

    /**
     * @return String list of tags
     * 
     */
    public Output<Optional<List<String>>> tags() {
        return Codegen.optional(this.tags);
    }
    /**
     * Fabric Token from the [Equinix Fabric Portal](https://ecxfabric.equinix.com/dashboard)
     * 
     */
    @Export(name="token", type=String.class, parameters={})
    private Output<String> token;

    /**
     * @return Fabric Token from the [Equinix Fabric Portal](https://ecxfabric.equinix.com/dashboard)
     * 
     */
    public Output<String> token() {
        return this.token;
    }
    /**
     * Connection type - dedicated or shared
     * 
     */
    @Export(name="type", type=String.class, parameters={})
    private Output<String> type;

    /**
     * @return Connection type - dedicated or shared
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Connection(String name) {
        this(name, ConnectionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Connection(String name, ConnectionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Connection(String name, ConnectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("equinix-metal:index/connection:Connection", name, args == null ? ConnectionArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Connection(String name, Output<String> id, @Nullable ConnectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("equinix-metal:index/connection:Connection", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Connection get(String name, Output<String> id, @Nullable ConnectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Connection(name, id, state, options);
    }
}
