// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.equinixmetal;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.equinixmetal.DeviceNetworkTypeArgs;
import com.pulumi.equinixmetal.Utilities;
import com.pulumi.equinixmetal.inputs.DeviceNetworkTypeState;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * 
 * See the Network Types Guide for examples of this resource and to learn about the recommended `equinix-metal.Port` alternative.
 * 
 * ## Import
 * 
 * This resource can also be imported using existing device ID
 * 
 * ```sh
 *  $ pulumi import equinix-metal:index/deviceNetworkType:DeviceNetworkType metal_device_network_type {existing device_id}
 * ```
 * 
 */
@ResourceType(type="equinix-metal:index/deviceNetworkType:DeviceNetworkType")
public class DeviceNetworkType extends com.pulumi.resources.CustomResource {
    /**
     * The ID of the device on which the network type should be set.
     * 
     */
    @Export(name="deviceId", refs={String.class}, tree="[0]")
    private Output<String> deviceId;

    /**
     * @return The ID of the device on which the network type should be set.
     * 
     */
    public Output<String> deviceId() {
        return this.deviceId;
    }
    /**
     * Network type to set. Must be one of `layer3`, `hybrid`, `layer2-individual` and `layer2-bonded`.
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    /**
     * @return Network type to set. Must be one of `layer3`, `hybrid`, `layer2-individual` and `layer2-bonded`.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DeviceNetworkType(String name) {
        this(name, DeviceNetworkTypeArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DeviceNetworkType(String name, DeviceNetworkTypeArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DeviceNetworkType(String name, DeviceNetworkTypeArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("equinix-metal:index/deviceNetworkType:DeviceNetworkType", name, args == null ? DeviceNetworkTypeArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private DeviceNetworkType(String name, Output<String> id, @Nullable DeviceNetworkTypeState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("equinix-metal:index/deviceNetworkType:DeviceNetworkType", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DeviceNetworkType get(String name, Output<String> id, @Nullable DeviceNetworkTypeState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DeviceNetworkType(name, id, state, options);
    }
}
