// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.equinixmetal;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.equinixmetal.Utilities;
import com.pulumi.equinixmetal.VirtualCircuitArgs;
import com.pulumi.equinixmetal.inputs.VirtualCircuitState;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Use this resource to associate VLAN with a Dedicated Port from [Equinix Fabric - software-defined interconnections](https://metal.equinix.com/developers/docs/networking/fabric/#associating-a-vlan-with-a-dedicated-port).
 * 
 * ## Example Usage
 * 
 * Pick an existing Project and Connection, create a VLAN and use `equinix-metal.VirtualCircuit` to associate it with a Primary Port of the Connection.
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.equinixmetal.EquinixmetalFunctions;
 * import com.pulumi.equinixmetal.inputs.GetConnectionArgs;
 * import com.pulumi.equinixmetal.Vlan;
 * import com.pulumi.equinixmetal.VlanArgs;
 * import com.pulumi.equinixmetal.VirtualCircuit;
 * import com.pulumi.equinixmetal.VirtualCircuitArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         final var projectId = &#34;52000fb2-ee46-4673-93a8-de2c2bdba33c&#34;;
 * 
 *         final var connId = &#34;73f12f29-3e19-43a0-8e90-ae81580db1e0&#34;;
 * 
 *         final var testConnection = Equinix-metalFunctions.getConnection(GetConnectionArgs.builder()
 *             .connectionId(connId)
 *             .build());
 * 
 *         var testVlan = new Vlan(&#34;testVlan&#34;, VlanArgs.builder()        
 *             .projectId(projectId)
 *             .metro(testConnection.applyValue(getConnectionResult -&gt; getConnectionResult.metro()))
 *             .build());
 * 
 *         var testVirtualCircuit = new VirtualCircuit(&#34;testVirtualCircuit&#34;, VirtualCircuitArgs.builder()        
 *             .connectionId(connId)
 *             .projectId(projectId)
 *             .portId(testConnection.applyValue(getConnectionResult -&gt; getConnectionResult.ports()[0].id()))
 *             .vlanId(testVlan.id())
 *             .nniVlan(1056)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 */
@ResourceType(type="equinix-metal:index/virtualCircuit:VirtualCircuit")
public class VirtualCircuit extends com.pulumi.resources.CustomResource {
    /**
     * UUID of Connection where the VC is scoped to
     * 
     */
    @Export(name="connectionId", refs={String.class}, tree="[0]")
    private Output<String> connectionId;

    /**
     * @return UUID of Connection where the VC is scoped to
     * 
     */
    public Output<String> connectionId() {
        return this.connectionId;
    }
    /**
     * Description for the Virtual Circuit resource
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Description for the Virtual Circuit resource
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Name of the Virtual Circuit resource
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Name of the Virtual Circuit resource
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Equinix Metal network-to-network VLAN ID
     * 
     */
    @Export(name="nniVlan", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> nniVlan;

    /**
     * @return Equinix Metal network-to-network VLAN ID
     * 
     */
    public Output<Optional<Integer>> nniVlan() {
        return Codegen.optional(this.nniVlan);
    }
    /**
     * Nni VLAN ID parameter, see https://metal.equinix.com/developers/docs/networking/fabric/
     * 
     */
    @Export(name="nniVnid", refs={Integer.class}, tree="[0]")
    private Output<Integer> nniVnid;

    /**
     * @return Nni VLAN ID parameter, see https://metal.equinix.com/developers/docs/networking/fabric/
     * 
     */
    public Output<Integer> nniVnid() {
        return this.nniVnid;
    }
    /**
     * UUID of the Connection Port where the VC is scoped to
     * 
     */
    @Export(name="portId", refs={String.class}, tree="[0]")
    private Output<String> portId;

    /**
     * @return UUID of the Connection Port where the VC is scoped to
     * 
     */
    public Output<String> portId() {
        return this.portId;
    }
    /**
     * UUID of the Project where the VC is scoped to
     * 
     */
    @Export(name="projectId", refs={String.class}, tree="[0]")
    private Output<String> projectId;

    /**
     * @return UUID of the Project where the VC is scoped to
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }
    /**
     * Speed of the Virtual Circuit resource
     * 
     */
    @Export(name="speed", refs={String.class}, tree="[0]")
    private Output<String> speed;

    /**
     * @return Speed of the Virtual Circuit resource
     * 
     */
    public Output<String> speed() {
        return this.speed;
    }
    /**
     * Status of the virtal circuit
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return Status of the virtal circuit
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * Tags for the Virtual Circuit resource
     * 
     */
    @Export(name="tags", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> tags;

    /**
     * @return Tags for the Virtual Circuit resource
     * 
     */
    public Output<Optional<List<String>>> tags() {
        return Codegen.optional(this.tags);
    }
    /**
     * UUID of the VLAN to associate
     * 
     */
    @Export(name="vlanId", refs={String.class}, tree="[0]")
    private Output<String> vlanId;

    /**
     * @return UUID of the VLAN to associate
     * 
     */
    public Output<String> vlanId() {
        return this.vlanId;
    }
    /**
     * VNID VLAN parameter, see https://metal.equinix.com/developers/docs/networking/fabric/
     * 
     */
    @Export(name="vnid", refs={Integer.class}, tree="[0]")
    private Output<Integer> vnid;

    /**
     * @return VNID VLAN parameter, see https://metal.equinix.com/developers/docs/networking/fabric/
     * 
     */
    public Output<Integer> vnid() {
        return this.vnid;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public VirtualCircuit(String name) {
        this(name, VirtualCircuitArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public VirtualCircuit(String name, VirtualCircuitArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public VirtualCircuit(String name, VirtualCircuitArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("equinix-metal:index/virtualCircuit:VirtualCircuit", name, args == null ? VirtualCircuitArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private VirtualCircuit(String name, Output<String> id, @Nullable VirtualCircuitState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("equinix-metal:index/virtualCircuit:VirtualCircuit", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static VirtualCircuit get(String name, Output<String> id, @Nullable VirtualCircuitState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new VirtualCircuit(name, id, state, options);
    }
}
