// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// The API auth key for API operations.
func GetAuthToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "equinix-metal:authToken")
}
func GetMaxRetries(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "equinix-metal:maxRetries")
}
func GetMaxRetryWaitSeconds(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "equinix-metal:maxRetryWaitSeconds")
}
