// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package equinix

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides an Equinix Metal metro datasource.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-equinix-metal/sdk/v3/go/equinix-metal"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		sv, err := equinix - metal.GetMetro(ctx, &equinix-metal.GetMetroArgs{
// 			Code: "sv",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("id", sv.Id)
// 		return nil
// 	})
// }
// ```
func GetMetro(ctx *pulumi.Context, args *GetMetroArgs, opts ...pulumi.InvokeOption) (*GetMetroResult, error) {
	var rv GetMetroResult
	err := ctx.Invoke("equinix-metal:index/getMetro:getMetro", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getMetro.
type GetMetroArgs struct {
	// The metro code
	Code string `pulumi:"code"`
}

// A collection of values returned by getMetro.
type GetMetroResult struct {
	// The code of the metro
	Code string `pulumi:"code"`
	// The country of the metro
	Country string `pulumi:"country"`
	// The ID of the metro
	Id string `pulumi:"id"`
	// The name of the metro
	Name string `pulumi:"name"`
}
