// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package equinix

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to read ports of existing devices. You can read port by either its UUID, or by a device UUID and port name.
//
// ## Example Usage
//
// Create a device and read it's eth0 port to the datasource.
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-equinix-metal/sdk/v3/go/equinix-metal"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		projectId := "<UUID_of_your_project>"
// 		testDevice, err := equinix - metal.NewDevice(ctx, "testDevice", &equinix-metal.DeviceArgs{
// 			Hostname: pulumi.String("tfacc-test-device-port"),
// 			Plan:     pulumi.String("c3.medium.x86"),
// 			Facilities: pulumi.StringArray{
// 				pulumi.String("sv15"),
// 			},
// 			OperatingSystem: pulumi.String("ubuntu_20_04"),
// 			BillingCycle:    pulumi.String("hourly"),
// 			ProjectId:       pulumi.String(projectId),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupPort(ctx *pulumi.Context, args *LookupPortArgs, opts ...pulumi.InvokeOption) (*LookupPortResult, error) {
	var rv LookupPortResult
	err := ctx.Invoke("equinix-metal:index/getPort:getPort", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPort.
type LookupPortArgs struct {
	DeviceId *string `pulumi:"deviceId"`
	// Whether to look for public or private block.
	Name   *string `pulumi:"name"`
	PortId *string `pulumi:"portId"`
}

// A collection of values returned by getPort.
type LookupPortResult struct {
	// UUID of the bond port"
	BondId string `pulumi:"bondId"`
	// Name of the bond port
	BondName string `pulumi:"bondName"`
	// Flag indicating whether the port is bonded
	Bonded   bool    `pulumi:"bonded"`
	DeviceId *string `pulumi:"deviceId"`
	// Flag indicating whether the port can be removed from a bond
	DisbondSupported bool `pulumi:"disbondSupported"`
	// The provider-assigned unique ID for this managed resource.
	Id     string `pulumi:"id"`
	Layer2 bool   `pulumi:"layer2"`
	// MAC address of the port
	Mac  string `pulumi:"mac"`
	Name string `pulumi:"name"`
	// UUID of native VLAN of the port
	NativeVlanId string `pulumi:"nativeVlanId"`
	// One of layer2-bonded, layer2-individual, layer3, hybrid, hybrid-bonded
	NetworkType string  `pulumi:"networkType"`
	PortId      *string `pulumi:"portId"`
	// Type is either "NetworkBondPort" for bond ports or "NetworkPort" for bondable ethernet ports
	Type string `pulumi:"type"`
	// UUIDs of attached VLANs
	VlanIds []string `pulumi:"vlanIds"`
	// VXLAN ids of attached VLANs
	VxlanIds []int `pulumi:"vxlanIds"`
}
