// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package equinix

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Datasource `Volume` was removed in version 3.0.0, and the API support was deprecated on June 1st 2021. See https://metal.equinix.com/developers/docs/storage/elastic-block-storage/#elastic-block-storage for more details.
func LookupVolume(ctx *pulumi.Context, args *LookupVolumeArgs, opts ...pulumi.InvokeOption) (*LookupVolumeResult, error) {
	var rv LookupVolumeResult
	err := ctx.Invoke("equinix-metal:index/getVolume:getVolume", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVolume.
type LookupVolumeArgs struct {
	Name      *string `pulumi:"name"`
	ProjectId *string `pulumi:"projectId"`
	VolumeId  *string `pulumi:"volumeId"`
}

// A collection of values returned by getVolume.
type LookupVolumeResult struct {
	BillingCycle string   `pulumi:"billingCycle"`
	Created      string   `pulumi:"created"`
	Description  string   `pulumi:"description"`
	DeviceIds    []string `pulumi:"deviceIds"`
	Facility     string   `pulumi:"facility"`
	// The provider-assigned unique ID for this managed resource.
	Id               string                    `pulumi:"id"`
	Locked           bool                      `pulumi:"locked"`
	Name             string                    `pulumi:"name"`
	Plan             string                    `pulumi:"plan"`
	ProjectId        string                    `pulumi:"projectId"`
	Size             int                       `pulumi:"size"`
	SnapshotPolicies []GetVolumeSnapshotPolicy `pulumi:"snapshotPolicies"`
	State            string                    `pulumi:"state"`
	Updated          string                    `pulumi:"updated"`
	VolumeId         string                    `pulumi:"volumeId"`
}
