// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.equinixmetal.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetFacilityCapacity {
    /**
     * @return device plan to check
     * 
     */
    private String plan;
    /**
     * @return number of device to check
     * 
     */
    private @Nullable Integer quantity;

    private GetFacilityCapacity() {}
    /**
     * @return device plan to check
     * 
     */
    public String plan() {
        return this.plan;
    }
    /**
     * @return number of device to check
     * 
     */
    public Optional<Integer> quantity() {
        return Optional.ofNullable(this.quantity);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetFacilityCapacity defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String plan;
        private @Nullable Integer quantity;
        public Builder() {}
        public Builder(GetFacilityCapacity defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.plan = defaults.plan;
    	      this.quantity = defaults.quantity;
        }

        @CustomType.Setter
        public Builder plan(String plan) {
            this.plan = Objects.requireNonNull(plan);
            return this;
        }
        @CustomType.Setter
        public Builder quantity(@Nullable Integer quantity) {
            this.quantity = quantity;
            return this;
        }
        public GetFacilityCapacity build() {
            final var o = new GetFacilityCapacity();
            o.plan = plan;
            o.quantity = quantity;
            return o;
        }
    }
}
