// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.EquinixMetal.Inputs
{

    public sealed class VolumeSnapshotPolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("snapshotCount", required: true)]
        public Input<int> SnapshotCount { get; set; } = null!;

        [Input("snapshotFrequency", required: true)]
        public Input<string> SnapshotFrequency { get; set; } = null!;

        public VolumeSnapshotPolicyArgs()
        {
        }
        public static new VolumeSnapshotPolicyArgs Empty => new VolumeSnapshotPolicyArgs();
    }
}
