// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.equinixmetal.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.equinixmetal.inputs.GetMetroCapacity;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetMetroPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetMetroPlainArgs Empty = new GetMetroPlainArgs();

    /**
     * (Optional) Ensure that queried metro has capacity for specified number of given plans
     * 
     */
    @Import(name="capacities")
    private @Nullable List<GetMetroCapacity> capacities;

    /**
     * @return (Optional) Ensure that queried metro has capacity for specified number of given plans
     * 
     */
    public Optional<List<GetMetroCapacity>> capacities() {
        return Optional.ofNullable(this.capacities);
    }

    /**
     * The metro code
     * 
     */
    @Import(name="code", required=true)
    private String code;

    /**
     * @return The metro code
     * 
     */
    public String code() {
        return this.code;
    }

    private GetMetroPlainArgs() {}

    private GetMetroPlainArgs(GetMetroPlainArgs $) {
        this.capacities = $.capacities;
        this.code = $.code;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetMetroPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetMetroPlainArgs $;

        public Builder() {
            $ = new GetMetroPlainArgs();
        }

        public Builder(GetMetroPlainArgs defaults) {
            $ = new GetMetroPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param capacities (Optional) Ensure that queried metro has capacity for specified number of given plans
         * 
         * @return builder
         * 
         */
        public Builder capacities(@Nullable List<GetMetroCapacity> capacities) {
            $.capacities = capacities;
            return this;
        }

        /**
         * @param capacities (Optional) Ensure that queried metro has capacity for specified number of given plans
         * 
         * @return builder
         * 
         */
        public Builder capacities(GetMetroCapacity... capacities) {
            return capacities(List.of(capacities));
        }

        /**
         * @param code The metro code
         * 
         * @return builder
         * 
         */
        public Builder code(String code) {
            $.code = code;
            return this;
        }

        public GetMetroPlainArgs build() {
            $.code = Objects.requireNonNull($.code, "expected parameter 'code' to be non-null");
            return $;
        }
    }

}
