// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.equinixmetal.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPortPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetPortPlainArgs Empty = new GetPortPlainArgs();

    @Import(name="deviceId")
    private @Nullable String deviceId;

    public Optional<String> deviceId() {
        return Optional.ofNullable(this.deviceId);
    }

    /**
     * Whether to look for public or private block.
     * 
     */
    @Import(name="name")
    private @Nullable String name;

    /**
     * @return Whether to look for public or private block.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="portId")
    private @Nullable String portId;

    public Optional<String> portId() {
        return Optional.ofNullable(this.portId);
    }

    private GetPortPlainArgs() {}

    private GetPortPlainArgs(GetPortPlainArgs $) {
        this.deviceId = $.deviceId;
        this.name = $.name;
        this.portId = $.portId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPortPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPortPlainArgs $;

        public Builder() {
            $ = new GetPortPlainArgs();
        }

        public Builder(GetPortPlainArgs defaults) {
            $ = new GetPortPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder deviceId(@Nullable String deviceId) {
            $.deviceId = deviceId;
            return this;
        }

        /**
         * @param name Whether to look for public or private block.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        public Builder portId(@Nullable String portId) {
            $.portId = portId;
            return this;
        }

        public GetPortPlainArgs build() {
            return $;
        }
    }

}
